routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\LoginController@showLoginForm')->name('login');

Auth::routes();

Route::prefix('dashboard')->group(function(){

    Route::get('/', 'HomeController@index')->name('dashboard');
    Route::resource('/spp', 'SppController');
    Route::resource('/kelas', 'KelasController', ['parameters' => ['kelas' => 'kelas']]);
    Route::resource('/siswa', 'SiswaController');
    Route::resource('/pembayaran', 'PembayaranController');
    Route::get('/laporan', 'LaporanController@index')->name('laporan');
    Route::get('/laporan/generatePDF', 'LaporanController@exportPDF')->name('generateLaporan');
    Route::get('/laporan/generateExel', 'LaporanController@exportExel')->name('generateLaporanExel');
    Route::get('/historiPembayaran', 'HistoriController@index')->name('histori');
    Route::resource('/petugas', 'PetugasController', ['parameters' => ['petugas' => 'petugas']]);

});

app/Http/Controllers/PetugasController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Alert;
use Hash;
use Illuminate\Http\Request;

class PetugasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $petugas = User::all();
        return view('dashboard.petugas.index', compact('petugas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.petugas.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'email' => 'required|email|unique:users',
            'level' => 'required',
            'password' => 'required|confirmed',
        ]);
        
        User::create([
            'name' => $request->name,
            'email' => $request->email,
            'level' => $request->level,
            'password' => Hash::make($request->password)
        ]);

        Alert::success('Berhasil', 'Data Berhasil Ditambahkan');
        return redirect()->route('petugas.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $petugas = User::where('id' ,$id)->first();
        return view('dashboard.petugas.profile', compact('petugas'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $petugas = User::where('id', $id)->first();
        return view('dashboard.petugas.edit', compact('petugas'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required',
            'email' => 'required|email',
            'level' => 'required',
            'password' => 'confirmed',
        ]);
        if($petugas = User::where('id', $id)->get()){
            if(empty($request->password)) {
                User::where('id', $id)
                ->update([
                    'name' => $request->name,
                    'email' => $request->email,
                    'level' => $request->level,
                ]);
            } else {
                User::where('id', $id)
                ->update([
                    'name' => $request->name,
                    'email' => $request->email,
                    'level' => $request->level,
                    'password' => Hash::make($request->password)
                ]);
            }
        }

        Alert::success('Berhasil', 'Data Berhasil Diubah');
        return redirect()->route('petugas.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::destroy($id);
        Alert::success('Berhasil','Data Berhasil Dihapus');
        return back();
    }
}

resources/views/dashboard/petugas/create.blade.php
@extends('layouts.main')

@section('title', 'Tambah Data Petugas | Pembayaran SPP')

{{-- for header in content --}}
@section('header')
<div class="page-header row no-gutters py-4">
    <div class="col-12 text-center text-sm-left mb-0">
        <span class="text-uppercase page-subtitle">Data Petugas</span>
        <h3 class="page-title">Petugas</h3>
    </div>
</div>
@endsection
{{-- end header content --}}

{{-- main content --}}
@section('content')
<div class="row">
    <!-- input transaksi pembayaran -->
    <div class="col-12 mb-4">
        <div class="card card-small">
            <div class="card-header border-bottom">
                <h6 class="m-0">Data Petugas</h6>
            </div>
            <div class="card-body pt-3">
                <form action="{{ route('petugas.store') }}" method="post">@csrf

                    <div class="form-group">
                        <label for="name">Nama</label>
                        <input type="text" class="form-control form-control-sm @error('name') is-invalid @enderror"
                            id="name" name="name" value="{{ old('name') }}">
                        @error('name')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="level">Level</label>
                        <select class="form-control form-control-sm @error('level') is-invalid @enderror" id="level"
                            name="level">
                            <option value="">Pilih Level</option>
                            <option value="admin">Admin</option>
                            <option value="petugas">Petugas</option>
                        </select>
                        @error('level')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="email">email</label>
                        <input type="email" class="form-control form-control-sm @error('email') is-invalid @enderror"
                            id="email" name="email" value="{{ old('email') }}">
                        @error('email')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password"
                            class="form-control form-control-sm @error('password') is-invalid @enderror" id="password"
                            name="password">
                        @error('password')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="password_confirmation">Konfirmasi</label>
                        <input type="password"
                            class="form-control form-control-sm @error('password') is-invalid @enderror"
                            id="password_confirmation" name="password_confirmation">
                    </div>
                    <a href="{{ route('petugas.index') }}" class="btn btn-danger float-left">Kembali</a>
                    <button type="submit" class="btn btn-primary float-right">Simpan</button>
                </form>
            </div>
        </div>
    </div>
    {{-- end of input transaksi pembayaran --}}
</div>

@endsection
{{-- end content --}}

@section('js')
<script>
    $(function() {
        const level = '{{ old("level") }}';
        if(level !== '') {
            $('#level').val(level);
        }



        $('input').on('keyup', function() {
            $(this).removeClass('is-invalid');
        })
        $('select').on('change', function() {
            $(this).removeClass('is-invalid');
        })
        
    });

    // for deleting data
    function deleteData(id) {
            Swal.fire({
                title: 'Apakah Anda Yakin?',
                text: "Data yang di hapus tidak dapat di kembalikan!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Ya, Hapus',
                cancelButtonText: 'Kembali',
            }).then((result) => {
                if (result.value) {
                    $('#formDeletePetugas-' + id).submit();
                }
            })
        }
</script>
@endsection

resources/views/dashboard/petugas/edit.blade.php
@extends('layouts.main')

@section('title', 'Edit Data Petugas | Pembayaran SPP')

{{-- for header in content --}}
@section('header')
<div class="page-header row no-gutters py-4">
    <div class="col-12 text-center text-sm-left mb-0">
        <span class="text-uppercase page-subtitle">Edit Data Petugas</span>
        <h3 class="page-title">Petugas</h3>
    </div>
</div>
@endsection
{{-- end header content --}}

{{-- main content --}}
@section('content')
<div class="row">
    <!-- input transaksi pembayaran -->
    <div class="col-12 mb-4">
        <div class="card card-small">
            <div class="card-header border-bottom">
                <h6 class="m-0">Edit Data Petugas</h6>
            </div>
            <div class="card-body pt-3">
                <form action="{{ route('petugas.update', ['id' => $petugas->id]) }}" method="post">@csrf @method('put')

                    <div class="form-group">
                        <label for="name">Nama</label>
                        <input type="text" class="form-control form-control-sm @error('name') is-invalid @enderror"
                            id="name" name="name" value="{{ $petugas->name }}">
                        @error('name')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="level">Level</label>
                        <select class="form-control form-control-sm @error('level') is-invalid @enderror" id="level"
                            name="level">
                            <option value="">Pilih Level</option>
                            <option value="admin">Admin</option>
                            <option value="petugas">Petugas</option>
                        </select>
                        @error('level')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="email">email</label>
                        <input type="email" class="form-control form-control-sm @error('email') is-invalid @enderror"
                            id="email" name="email" value="{{ $petugas->email }}">
                        @error('email')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="password">Password (Optional)</label>
                        <input type="password"
                            class="form-control form-control-sm @error('password') is-invalid @enderror" id="password"
                            name="password">
                        @error('password')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="password_confirmation">Konfirmasi (Optional)</label>
                        <input type="password"
                            class="form-control form-control-sm @error('password') is-invalid @enderror"
                            id="password_confirmation" name="password_confirmation">
                    </div>
                    <a href="{{ route('petugas.index') }}" class="btn btn-danger float-left">Kembali</a>
                    <button type="submit" class="btn btn-primary float-right">Simpan</button>
                </form>
            </div>
        </div>
    </div>
    {{-- end of input transaksi pembayaran --}}
</div>

@endsection
{{-- end content --}}

@section('js')
<script>
    $(function() {
        const level = '{{ $petugas->level }}';
        if(level !== '') {
            $('#level').val(level);
        }

        $('input').on('keyup', function() {
            $(this).removeClass('is-invalid');
        })
        $('select').on('change', function() {
            $(this).removeClass('is-invalid');
        })
        
    });

    // for deleting data
    function deleteData(id) {
            Swal.fire({
                title: 'Apakah Anda Yakin?',
                text: "Data yang di hapus tidak dapat di kembalikan!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Ya, Hapus',
                cancelButtonText: 'Kembali',
            }).then((result) => {
                if (result.value) {
                    $('#formDeletePetugas-' + id).submit();
                }
            })
        }
</script>
@endsection

resources/views/dashboard/petugas/index.blade.php
@extends('layouts.main')

@section('title', 'Data Petugas | Pembayaran SPP')

{{-- for header in content --}}
@section('header')
<div class="page-header row no-gutters py-4">
    <div class="col-12 text-center text-sm-left mb-0">
        <span class="text-uppercase page-subtitle">Data Petugas</span>
        <h3 class="page-title">Petugas</h3>
    </div>
</div>
@endsection
{{-- end header content --}}

{{-- main content --}}
@section('content')
<div class="row">
    <!-- input transaksi pembayaran -->
    <div class="col-12 mb-4">
        <div class="card card-small">
            <div class="card-header border-bottom">
                <h6 class="m-0">Data Petugas</h6>
            </div>
            <div class="card-body pt-3">
                <div class="row">
                    <div class="col-12 my-2">
                        <a href="{{ route('petugas.create') }}" class="shadow btn btn-success">Tambah Data Petugas</a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 overflow-auto">
                        <table class="table mb-0 text-center">
                            <thead class="bg-light">
                                <tr>
                                    <th scope="col" class="border-0">#</th>
                                    <th scope="col" class="border-0">Nama</th>
                                    <th scope="col" class="border-0">Email</th>
                                    <th scope="col" class="border-0">Level</th>
                                    <th scope="col" class="border-0">Dibuat</th>
                                    <th scope="col" class="border-0">Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($petugas as $p)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $p->name }}</td>
                                    <td>{{ $p->email }}</td>
                                    <td>{{ $p->level }}</td>
                                    <td>{{ $p->created_at->format('H:i, d M y') }}</td>
                                    <td>
                                        <a href="{{ route('petugas.edit', ['id' => $p->id]) }}"
                                            class="btn btn-primary">Edit</a>
                                        <form action="{{ route('petugas.destroy', ['id' => $p->id]) }}"
                                            class="d-inline-block" id="formDeletePetugas-{{ $p->id }}" method="post">
                                            @csrf @method('delete')
                                            <button type="button" class="btn btn-danger"
                                                onclick="deleteData({{ $p->id }})">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {{-- end of input transaksi pembayaran --}}
</div>

@endsection
{{-- end content --}}

@section('js')
<script>
    // for deleting data
 function deleteData(id) {
        Swal.fire({
            title: 'Apakah Anda Yakin?',
            text: "Data yang di hapus tidak dapat di kembalikan!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Ya, Hapus',
            cancelButtonText: 'Kembali',
        }).then((result) => {
            if (result.value) {
                $('#formDeletePetugas-' + id).submit();
            }
        })
    }
</script>
@endsection

resources/views/dashboard/petugas/profile.blade.php
@extends('layouts.main')

@section('title', 'Edit Data Petugas | Pembayaran SPP')

{{-- for header in content --}}
@section('header')
<div class="page-header row no-gutters py-4">
    <div class="col-12 text-center text-sm-left mb-0">
        <span class="text-uppercase page-subtitle">Profile Petugas</span>
        <h3 class="page-title">Profile</h3>
    </div>
</div>
@endsection
{{-- end header content --}}

{{-- main content --}}
@section('content')
<div class="row">
    <!-- input transaksi pembayaran -->
    <div class="col-12 mb-4">
        <div class="card card-small">
            <div class="card-header border-bottom">
                <h6 class="m-0">Profile</h6>
            </div>
            <div class="card-body pt-3">
                <form action="{{ route('petugas.update', ['id' => $petugas->id]) }}" method="post">@csrf @method('put')
                    <div class="form-group">
                        <label for="name">Nama</label>
                        <input type="text" class="form-control form-control-sm @error('name') is-invalid @enderror"
                            id="name" name="name" value="{{ $petugas->name }}">
                        @error('name')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="level">Level</label>
                        <select class="form-control form-control-sm @error('level') is-invalid @enderror" id="level"
                            name="level">
                            <option value="">Pilih Level</option>
                            <option value="admin">Admin</option>
                            <option value="petugas">Petugas</option>
                        </select>
                        @error('level')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="email">email</label>
                        <input type="email" class="form-control form-control-sm @error('email') is-invalid @enderror"
                            id="email" name="email" value="{{ $petugas->email }}">
                        @error('email')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="password">Password (Optional)</label>
                        <input type="password"
                            class="form-control form-control-sm @error('password') is-invalid @enderror" id="password"
                            name="password">
                        @error('password')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="password_confirmation">Konfirmasi (Optional)</label>
                        <input type="password"
                            class="form-control form-control-sm @error('password') is-invalid @enderror"
                            id="password_confirmation" name="password_confirmation">
                    </div>
                    <a href="{{ route('dashboard') }}" class="btn btn-danger float-left">Kembali</a>
                    <button type="submit" class="btn btn-primary float-right">Simpan</button>
                </form>
            </div>
        </div>
    </div>
    {{-- end of input transaksi pembayaran --}}
</div>

@endsection
{{-- end content --}}

@section('js')
<script>
    $(function() {
        const level = '{{ $petugas->level }}';
        if(level !== '') {
            $('#level').val(level);
        }

        $('input').on('keyup', function() {
            $(this).removeClass('is-invalid');
        })
        $('select').on('change', function() {
            $(this).removeClass('is-invalid');
        })
        
    });

    // for deleting data
    function deleteData(id) {
            Swal.fire({
                title: 'Apakah Anda Yakin?',
                text: "Data yang di hapus tidak dapat di kembalikan!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Ya, Hapus',
                cancelButtonText: 'Kembali',
            }).then((result) => {
                if (result.value) {
                    $('#formDeletePetugas-' + id).submit();
                }
            })
        }
</script>
@endsection