routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\LoginController@showLoginForm')->name('login');

Auth::routes();

Route::prefix('dashboard')->group(function(){

    Route::get('/', 'HomeController@index')->name('dashboard');
    Route::resource('/spp', 'SppController');
    Route::resource('/kelas', 'KelasController', ['parameters' => ['kelas' => 'kelas']]);
    Route::resource('/siswa', 'SiswaController');
    Route::resource('/pembayaran', 'PembayaranController');
    Route::get('/laporan', 'LaporanController@index')->name('laporan');
    Route::get('/laporan/generatePDF', 'LaporanController@exportPDF')->name('generateLaporan');
    Route::get('/laporan/generateExel', 'LaporanController@exportExel')->name('generateLaporanExel');
    Route::get('/historiPembayaran', 'HistoriController@index')->name('histori');
    Route::resource('/petugas', 'PetugasController', ['parameters' => ['petugas' => 'petugas']]);

});

app/Spp.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Spp extends Model
{
    protected $table = 'spp';
    protected $fillable = ['tahun', 'nominal'];


    public function siswa()
    {
        return $this->hasMany(App\Siswa::class, 'id_kelas', 'id');
    }
}

app/Http/Controllers/SppController.php
<?php

namespace App\Http\Controllers;

use App\Spp;
use Illuminate\Http\Request;
use Alert;

class SppController extends Controller
{
    public function __construct() 
    {
        $this->middleware([
            'auth',
            'privilege:admin'
        ]);
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $spp = Spp::paginate(5);
        return view('dashboard.spp.index', compact('spp'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {}

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'tahun' => 'required|integer|min:4',
            'nominal' => 'required|integer'
        ]);
        Spp::create([
            'tahun' => $request->tahun,
            'nominal' => $request->nominal
        ]);
        Alert::success('Berhasil', 'Data Berhasil ditambahkan');
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Spp  $spp
     * @return \Illuminate\Http\Response
     */
    public function show(Spp $spp)
    {}

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Spp  $spp
     * @return \Illuminate\Http\Response
     */
    public function edit(Spp $spp)
    {
        return view('dashboard.spp.edit', compact('spp'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Spp  $spp
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Spp $spp)
    {
        $request->validate([
            'tahun' => 'required|integer|min:4',
            'nominal' => 'required|integer'
        ]);
        Spp::where('id', $spp->id)
                ->update([
                    'tahun' => $request->tahun,
                    'nominal' => $request->nominal
                ]);
        Alert::success('Berhasil', 'Data Berhasil diubah');
        return redirect()->route('spp.index');
    }

    /**
     * Remove the specified resource from storage.
     * !! Fix this, before all done 
     *
     * @param  \App\Spp  $spp
     * @return \Illuminate\Http\Response
     */
    public function destroy(Spp $spp)
    {
        $spp = Spp::destroy($spp->id);
        if($spp >= 0) {
            Alert::success('Berhasil', 'Data berhasil dihapus');
            return back();
        } else {
            Alert::error('Gagal', 'Silahkan Hubungi depeloper untuk informasi lebih lanjut');
            return back();
        }
    }
}

resources/views/dashboard/spp/edit.blade.php
@extends('layouts.main')


@section('title', 'SPP | Pembayaran SPP')

@section('header')
<div class="page-header row no-gutters py-4">
    <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
        <span class="text-uppercase page-subtitle">Edit Data Spp</span>
        <h3 class="page-title">SPP</h3>
    </div>
</div>
@endsection

@section('content')

<div class="row">
    <!-- form edit data -->
    <div class="col-12 col-sm-12 col-lg-8 mb-4">
        <div class="card card-small">
            <div class="card-header border-bottom">
                <h6 class="m-0">Edit Data SPP</h6>
            </div>
            <div class="card-body pt-3">
                <form action="{{ route('spp.update',['id' => $spp->id]) }}" method="POST">@csrf @method('put')
                    <div class="form-group">
                        <label for="tahun">Tahun</label>
                        <input type="number" class="form-control form-control-sm @error('tahun') is-invalid @enderror"
                            id="tahun" name="tahun" value="{{ $spp->tahun }}">
                        @error('tahun')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="nominal">Nominal</label>
                        <input type="number" class="form-control form-control-sm @error('nominal') is-invalid @enderror"
                            id="nominal" name="nominal" value="{{ $spp->nominal  }}">
                        @error('nominal')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>

                    <button type="submit" class="btn btn-primary btn-sm">Simpan</button>
                    <a href="{{ route('spp.index') }}" class="btn btn-danger btn-sm">kembali</a>
                </form>
            </div>
        </div>
    </div>
    <!-- end form edit data -->

</div>
@endsection


@section('js')
<script>
    $(function() {
        // for remove validation message on keyup
        $('input').on('keyup', function() {
            $(this).removeClass('is-invalid');
        })
    });
</script>
@endsection

resources/views/dashboard/spp/index.blade.php
@extends('layouts.main')


@section('title', 'SPP | Pembayaran SPP')

@section('header')
<div class="page-header row no-gutters py-4">
    <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
        <span class="text-uppercase page-subtitle">Data SPP</span>
        <h3 class="page-title">SPP</h3>
    </div>
</div>
@endsection

@section('content')

<div class="row">
    <!-- Users Stats -->
    <div class="col-12 col-sm-12 col-lg-6 mb-4">
        <div class="card card-small ">
            <div class="card-header border-bottom">
                <h6 class="m-0 d-inline-block">Data Data SPP</h6>
            </div>
            <div class="card-body pt-3 ">
                <form action="{{ route('spp.store') }}" method="POST">@csrf
                    <div class="form-group">
                        <label for="tahun">Tahun</label>
                        <input type="number" class="form-control form-control-sm @error('tahun') is-invalid @enderror"
                            id="tahun" name="tahun" value="{{ old('tahun') }}">
                        @error('tahun')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="nominal">Nominal</label>
                        <input type="number" class="form-control form-control-sm @error('nominal') is-invalid @enderror"
                            id="nominal" name="nominal" value="{{ old('nominal') }}">
                        @error('nominal')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>

                    <button type="submit" class="btn btn-primary btn-sm">Simpan</button>
                    <button type="reset" class="btn btn-secondary btn-sm">Reset</button>
                </form>
            </div>
        </div>
    </div>
    <!-- End Users Stats -->

    <!-- Users Stats -->
    <div class="col-12 col-sm-12 col-lg-6 mb-4">
        <div class="card card-small" style="min-height: 280px">
            <div class="card-header border-bottom">
                <h6 class="m-0 d-inline-block">Data SPP</h6>
            </div>
            <div class="card-body pt-3 overflow-auto">
                <table class="table mb-0 text-center">
                    <thead class="bg-light">
                        <tr>
                            <th scope="col" class="border-0">#</th>
                            <th scope="col" class="border-0">Tahun</th>
                            <th scope="col" class="border-0">Nominal</th>
                            <th scope="col" class="border-0">Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($spp as $s)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $s->tahun }}</td>
                            <td>{{ $s->nominal }}</td>
                            <td>
                                <a href="{{ route('spp.edit', ['id' => $s->id]) }}"
                                    class="btn btn-primary btn-sm">Edit</a>
                                <form action="{{ route('spp.destroy', ['id' => $s->id ]) }}" method="post"
                                    class="d-inline-block" id="formDeleteSpp-{{ $s->id }}">@csrf
                                    @method('delete')
                                    <button type="button" class="btn btn-danger btn-sm"
                                        onclick="deleteData({{ $s->id }})">Hapus</button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                <div class="float-right">
                    {{ $spp->links() }}
                </div>

            </div>
        </div>
    </div>
    <!-- End Users Stats -->
</div>
@endsection
@section('js')
<script>
    $(function() {
        // for checking validation on clicked button reset
        $('input').on('keyup', function() {
            $(this).removeClass('is-invalid');
        })
        $('button[type="reset"]').on('click', function() {
            $('input').removeClass('is-invalid');
        });
    });
    // for deleting data
    function deleteData(id) {
        Swal.fire({
            title: 'Apakah Anda Yakin?',
            text: "Data yang di hapus tidak dapat di kembalikan!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Ya, Hapus',
            cancelButtonText: 'Kembali',
        }).then((result) => {
            if (result.value) {
                $('#formDeleteSpp-' + id).submit();
            }
        })
    }
</script>
@endsection