routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\LoginController@showLoginForm')->name('login');

Auth::routes();

Route::prefix('dashboard')->group(function(){

    Route::get('/', 'HomeController@index')->name('dashboard');
    Route::resource('/spp', 'SppController');
    Route::resource('/kelas', 'KelasController', ['parameters' => ['kelas' => 'kelas']]);
    Route::resource('/siswa', 'SiswaController');
    Route::resource('/pembayaran', 'PembayaranController');
    Route::get('/laporan', 'LaporanController@index')->name('laporan');
    Route::get('/laporan/generatePDF', 'LaporanController@exportPDF')->name('generateLaporan');
    Route::get('/laporan/generateExel', 'LaporanController@exportExel')->name('generateLaporanExel');
    Route::get('/historiPembayaran', 'HistoriController@index')->name('histori');
    Route::resource('/petugas', 'PetugasController', ['parameters' => ['petugas' => 'petugas']]);

});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/main.blade.php
<!doctype html>
<html class="no-js h-100" lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>@yield('title')</title>
  <meta name="description"
    content="A high-quality &amp; free Bootstrap admin dashboard template pack that comes with lots of templates and components.">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" id="main-stylesheet" data-version="1.1.0"
    href="{{ asset('template/styles/shards-dashboards.1.1.0.min.css') }}">
  <link rel="stylesheet" href="{{ asset('template/styles/extras.1.1.0.min.css') }}">
  <script async defer src="https://buttons.github.io/buttons.js"></script>
  <link rel="stylesheet" type="text/css" href="{{ asset('css/loading-bar.css') }}" />
  <style>
    .swal2-container {
      z-index: 1071 !important;
    }

    div.paceDiv {
      position: absolute;
      width: 100%;
      height: 100%;
      display: none;
    }
  </style>
</head>

<body class="h-100">

  <div class="container-fluid">
    <div class="row">

      <!-- Main Sidebar -->
      @include('layouts.sidebar')
      <!-- End Main Sidebar -->

      <main class="main-content col-lg-10 col-md-9 col-sm-12 p-0 offset-lg-2 offset-md-3">

        <div class="main-navbar sticky-top bg-white">
          @include('layouts.navbar')
        </div>
        <!-- / .main-navbar -->


        <div class="main-content-container container-fluid px-4" id="pace">
          <!-- Page Header -->
          @yield('header')
          <!-- End Page Header -->

          <!-- Main Content -->
          @yield('content')
          <!-- End Main Content -->

        </div>

        <footer class="main-footer d-flex p-2 px-3 bg-white border-top">
          <span class="copyright ml-auto my-auto mr-2">Copyright © 2018
            <a href="https://designrevision.com" rel="nofollow">DesignRevision</a>
          </span>
        </footer>
      </main>
    </div>
  </div>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <form action="{{ route('logout') }}" method="post"> @csrf
            <button type="submit" class="btn btn-primary">Logout</button>
          </form>
        </div>
      </div>
    </div>
  </div>


  <script src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
  <script src="https://unpkg.com/shards-ui@latest/dist/js/shards.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Sharrre/2.0.1/jquery.sharrre.min.js"></script>
  <script src="{{ asset('template/scripts/extras.1.1.0.min.js') }}"></script>
  <script src="{{ asset('template/scripts/shards-dashboards.1.1.0.min.js') }}"></script>
  <script src="{{ asset('template/scripts/app/app-blog-overview.1.1.0.js') }}"></script>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
  @include('sweetalert::alert')
  <script type="text/javascript" src="{{ asset('js/loading-bar.js') }}"></script>
  @yield('js')

</body>

</html>

resources/views/layouts/navbar.blade.php
<!-- Main Navbar -->
<nav class="navbar align-items-stretch navbar-light flex-md-nowrap p-0">
    <form action="#" class="main-navbar__search w-100 d-none d-md-flex d-lg-flex">

    </form>
    <ul class="navbar-nav border-left flex-row ">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-nowrap px-3" data-toggle="dropdown" href="#" role="button"
                aria-haspopup="true" aria-expanded="false">
                <img class="user-avatar rounded-circle mr-2" width="40px"
                    src="{{ asset('img/' . Auth::user()->avatar) }}" alt="User Avatar">
                <span class="d-none d-md-inline-block">{{ Auth::user()->name }}</span>
            </a>
            <div class="dropdown-menu dropdown-menu-small">
                <a class="dropdown-item" href="{{ route('petugas.show', ['id' => Auth::user()->id]) }}">
                    <i class="material-icons">&#xE7FD;</i> Profile
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item " href="#" data-target="#logoutModal" data-toggle="modal">
                    <i class="material-icons ">&#xE879;</i>logout
                </a>
            </div>
        </li>
    </ul>

    <nav class="nav">
        <a href="#" class="nav-link nav-link-icon toggle-sidebar d-inline d-md-none d-lg-none text-center border-left"
            data-toggle="collapse" data-target=".header-navbar" aria-expanded="false" aria-controls="header-navbar">
            <i class="material-icons">&#xE5D2;</i>
        </a>
    </nav>
</nav>

resources/views/layouts/sidebar.blade.php
<aside class="main-sidebar col-12 col-md-3 col-lg-2 px-0">
    <div class="main-navbar">
        <nav class="navbar align-items-stretch navbar-light bg-white flex-md-nowrap border-bottom p-0">
            <a class="navbar-brand w-100 mr-0" href="{{ route('dashboard') }}" style="line-height: 25px;">
                <div class="d-table m-auto">
                    <img id="main-logo" class="d-inline-block align-top mr-1" style="max-width: 25px;"
                        src="{{ asset('template/images/shards-dashboards-logo.svg') }}" alt="Shards Dashboard">
                    <span class="d-none d-md-inline ml-1">Pembayaran SPP</span>
                </div>
            </a>
            <a class="toggle-sidebar d-sm-inline d-md-none d-lg-none">
                <i class="material-icons">&#xE5C4;</i>
            </a>
        </nav>
    </div>
    <form action="#" class="main-sidebar__search w-100 border-right d-none">
        <div class="input-group input-group-seamless ml-3">
            <div class="input-group-prepend">
                <div class="input-group-text">
                    <i class="fas fa-search"></i>
                </div>
            </div>
            <input class="navbar-search form-control" type="text" placeholder="Search for something..."
                aria-label="Search">
        </div>
    </form>

    <div class="nav-wrapper">

        <ul class="nav flex-column">

            <li class="nav-item">
                <a class="nav-link {{ (request()->segment(1) == 'dashboard' && empty(request()->segment(2))) ? 'active' : '' }}"
                    href="{{ route('dashboard') }}">
                    <i class="material-icons">edit</i>
                    <span>Dashboard </span>
                </a>
            </li>

            @if (Auth::user()->level == 'admin')
            <li class="nav-item">
                <a class="nav-link {{  (request()->segment(2) == 'petugas')? 'active' : '' }}"
                    href="{{ route('petugas.index') }}">
                    <i class="material-icons">emoji_people</i>
                    <span>Data Petugas </span>
                </a>
            </li>
            @endif

            @if (Auth::user()->level == 'admin')
            <li class="nav-item">
                <a class="nav-link {{  (request()->segment(2) == 'kelas')? 'active' : '' }}"
                    href="{{ route('kelas.index') }}">
                    <i class="material-icons">group</i>
                    <span>Kelas</span>
                </a>
            </li>
            @endif


            @if (Auth::user()->level == 'admin')
            <li class="nav-item">
                <a class="nav-link {{  (request()->segment(2) == 'spp')? 'active' : '' }}"
                    href="{{ route('spp.index') }}">
                    <i class="material-icons">local_atm</i>
                    <span>SPP</span>
                </a>
            </li>
            @endif


            <li class="nav-item">
                <a class="nav-link {{  (request()->segment(2) == 'siswa' ) ? 'active' : '' }}"
                    href="{{ route('siswa.index') }}">
                    <i class="material-icons ">sports_kabaddi</i>
                    <span>Siswa</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link {{  (request()->segment(2) == 'pembayaran')? 'active' : '' }}"
                    href="{{ route('pembayaran.index') }}">
                    <i class="material-icons">input</i>
                    <span>Input Pembayaran</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link {{  (request()->segment(2) == 'historiPembayaran' ) ? 'active' : '' }}"
                    href="{{ route('histori') }}">
                    <i class="material-icons ">local_post_office</i>
                    <span>Histori Pembayaran</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link {{  (request()->segment(2) == 'laporan')? 'active' : '' }}"
                    href="{{ route('laporan') }}">
                    <i class="material-icons">analytics</i>
                    <span>Generate Laporan</span>
                </a>
            </li>

        </ul>
    </div>
</aside>